# Generated by Django 4.1.6 on 2023-02-03 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="top_scores",
            new_name="top_scorer",
        ),
    ]
